<a href="https://colab.research.google.com/github/kaurroopak/UCS420/blob/main/Lab_Assignment_4_1_(CC).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lab Assignment 4
###Submitted by : Roopakjeet Kaur (102497013)

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:

a) Addition of 2 in all the element

b) Multiply 3 with all the elements

c) Divide every element by 2

In [1]:
import numpy as np
a = np.array([5,6,7,8,9])
print("Original array: ", a)

res1 = a+2
print("Array after addition of 2: ", res1)

res2 = a*3
print("Array after multiplication of 3: ", res2)

res3 = a/2
print("Array after division by 2: ", res3)

Original array:  [5 6 7 8 9]
Array after addition of 2:  [ 7  8  9 10 11]
Array after multiplication of 3:  [15 18 21 24 27]
Array after division by 2:  [2.5 3.  3.5 4.  4.5]


Q.2 Questions on Basic NumPy Array:

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

b) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
print("Original array 'arr': ", arr)

# reverse
rev_arr = arr[::-1]
print("Reversed array: ", rev_arr)

# most frequent
x = np.array([1,2,3,4,5,1,2,1,1,1])
print("\nOriginal array 'x': ", x)
print("Most frequent value: ", np.bincount(x).argmax())

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print("\nOriginal array 'y': ", y)
print("Most frequent value: ", np.bincount(y).argmax())

Original array 'arr':  [1 2 3 6 4 5]
Reversed array:  [5 4 6 3 2 1]

Original array 'x':  [1 2 3 4 5 1 2 1 1 1]
Most frequent value:  1

Original array 'y':  [1 1 1 2 3 4 2 4 3 3]
Most frequent value:  1


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:

a) Access 1st row, 2nd column

b) Access 3rd row, 1st column

In [3]:
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Original array: \n", arr_2d)

# access 1st row, 2nd column
print("\nElement at 1st row, 2nd column: ", arr_2d[0,1])

# access 3rd row, 1st column
print("Element at 3rd row, 1st column: ", arr_2d[2,0])

Original array: 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Element at 1st row, 2nd column:  20
Element at 3rd row, 1st column:  70


Q.4 Write program to create an 1-D NumPy array named <(Your Name)> with evenly spaced 25 numbers from 10 to 100 using linspace().

Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array.

Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [11]:
roopak_arr = np.linspace(10,100,25)
print("Original array:\n", roopak_arr)

print("\nDimensions of the array: ", roopak_arr.ndim)     #dimesnsion
print("Shape of the array: ", roopak_arr.shape)           #shape
print("Total elements in the array: ", roopak_arr.size)   #total elements
print("Data type of each element: ", roopak_arr.dtype)    #data type

#reshaping to find transpose
roopak_reshaped = roopak_arr.reshape(25,1)
print("\nReshaped (Transpose) array: \n", roopak_reshaped)

#transpose
roopak_transpose = roopak_arr.T
print("\nTranspose of the array: \n", roopak_transpose)
#The .T attribute does not affect the original 1-D array since transposition only changes multi-dimensional arrays.

Original array:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions of the array:  1
Shape of the array:  (25,)
Total elements in the array:  25
Data type of each element:  float64

Reshaped (Transpose) array: 
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transpose of the array: 
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<(your_name)> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35.

Compute the mean,median, max, min, unique elements.

Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<(your_name)>.

Resize the array to two rows and three columns and name it as resized_ ucs420_<(your_name)>.

In [18]:
ucs420_roopak = np.array([[10,20,30,40],
                          [50,60,70,80],
                          [90,15,20,35]])
print("Original array: \n", ucs420_roopak)

mean_value = np.mean(ucs420_roopak)   #mean
print("\nMean is: ", mean_value)

median_value = np.median(ucs420_roopak)    #median
print("Median is: ", median_value)

max_value = np.max(ucs420_roopak)   #max
print("Max value is: ", max_value)

min_value = np.min(ucs420_roopak)   #min
print("Min value is: ", min_value)

unique_elements = np.unique(ucs420_roopak)   #unique
print("Unique elements are: ", unique_elements)

#reshape to 4 rows and 3 columns
reshaped_ucs420_roopak = ucs420_roopak.reshape(4,3)
print("\nReshaped array (4x3): \n", reshaped_ucs420_roopak)

#resize to 2 rows and 3 columns
resized_ucs420_roopak = np.resize(ucs420_roopak, (2,3))
print("\nResized array (2x3): \n", resized_ucs420_roopak)

Original array: 
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean is:  43.333333333333336
Median is:  37.5
Max value is:  90
Min value is:  10
Unique elements are:  [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array (4x3): 
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array (2x3): 
 [[10 20 30]
 [40 50 60]]
